# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under tshe License.

# This file is generated by device/realme/even/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/even

PRODUCT_COPY_FILES += \
    vendor/realme/even/proprietary/product/vendor_overlay/30/lib/modules/bt_drv.ko:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/lib/modules/bt_drv.ko \
    vendor/realme/even/proprietary/product/vendor_overlay/30/lib/modules/fmradio_drv.ko:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/lib/modules/fmradio_drv.ko \
    vendor/realme/even/proprietary/product/vendor_overlay/30/lib/modules/gps_drv.ko:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/lib/modules/gps_drv.ko \
    vendor/realme/even/proprietary/product/vendor_overlay/30/lib/modules/wlan_drv_gen4m.ko:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/lib/modules/wlan_drv_gen4m.ko \
    vendor/realme/even/proprietary/product/vendor_overlay/30/lib/modules/wmt_chrdev_wifi.ko:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/lib/modules/wmt_chrdev_wifi.ko \
    vendor/realme/even/proprietary/product/vendor_overlay/30/lib/modules/wmt_drv.ko:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/lib/modules/wmt_drv.ko

PRODUCT_COPY_FILES += \
    vendor/realme/even/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/realme/even/proprietary/bin/vtservice:$(TARGET_COPY_OUT_SYSTEM)/bin/vtservice \
    vendor/realme/even/proprietary/product/etc/apns-conf.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/apns-conf.xml \
    vendor/realme/even/proprietary/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.vtservice.rc \
    vendor/realme/even/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/realme/even/proprietary/lib/libem_support_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libem_support_jni.so \
    vendor/realme/even/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/realme/even/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/realme/even/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/realme/even/proprietary/lib64/libem_support_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libem_support_jni.so \

# IMS blobs
PRODUCT_COPY_FILES += \
    vendor/realme/even/proprietary/lib/libcomutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcomutils.so \
    vendor/realme/even/proprietary/lib/libimsma.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimsma.so \
    vendor/realme/even/proprietary/lib/libimsma_adapt.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimsma_adapt.so \
    vendor/realme/even/proprietary/lib/libimsma_rtp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimsma_rtp.so \
    vendor/realme/even/proprietary/lib/libimsma_socketwrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimsma_socketwrapper.so \
    vendor/realme/even/proprietary/lib/libmtk_vt_service.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtk_vt_service.so \
    vendor/realme/even/proprietary/lib/libmtk_vt_wrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtk_vt_wrapper.so \
    vendor/realme/even/proprietary/lib/libmtkavenhancements.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtkavenhancements.so \
    vendor/realme/even/proprietary/lib/libmtkperf_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtkperf_client.so \
    vendor/realme/even/proprietary/lib/libsignal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsignal.so \
    vendor/realme/even/proprietary/lib/libsink.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsink.so \
    vendor/realme/even/proprietary/lib/libsource.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsource.so \
    vendor/realme/even/proprietary/lib/libvcodec_cap.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvcodec_cap.so \
    vendor/realme/even/proprietary/lib/libvcodec_capenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvcodec_capenc.so \
    vendor/realme/even/proprietary/lib/libvt_avsync.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvt_avsync.so \
    vendor/realme/even/proprietary/system_ext/lib/vendor.mediatek.hardware.videotelephony@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/realme/even/proprietary/vendor/lib/vendor.mediatek.hardware.videotelephony@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/realme/even/proprietary/lib64/libmtk_vt_wrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmtk_vt_wrapper.so \
    vendor/realme/even/proprietary/lib64/libmtkavenhancements.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmtkavenhancements.so \
    vendor/realme/even/proprietary/lib64/libmtkperf_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmtkperf_client.so \
    vendor/realme/even/proprietary/lib64/libvcodec_cap.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libvcodec_cap.so \
    vendor/realme/even/proprietary/lib64/libvcodec_capenc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libvcodec_capenc.so \
    vendor/realme/even/proprietary/system_ext/lib64/vendor.mediatek.hardware.videotelephony@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/realme/even/proprietary/vendor/lib64/vendor.mediatek.hardware.videotelephony@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.mediatek.hardware.videotelephony@1.0.so 
    vendor/realme/even/proprietary/vendor/lib/hw/audio.primary.mt6768.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.mt6768.so \
    vendor/realme/even/proprietary/vendor/lib/hw/audio.r_submix.mt6768.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.r_submix.mt6768.so \
    vendor/realme/even/proprietary/vendor/lib/hw/audio.usb.mt6768.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.usb.mt6768.so \
    vendor/realme/even/proprietary/vendor/lib/hw/vendor.mediatek.hardware.bluetooth.audio@2.1-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vendor.mediatek.hardware.bluetooth.audio@2.1-impl.so \
    vendor/realme/even/proprietary/vendor/etc/init/audiocmdservice_atci.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/audiocmdservice_atci.rc \
    
    vendor/realme/even/proprietary/vendor/lib/libaudio_engineer_test.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio_engineer_test.so \
    vendor/realme/even/proprietary/vendor/lib/libaudio_param_parser-vnd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio_param_parser-vnd.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiocompensationfilter_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocompensationfilter_vendor.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiocompensationfilterc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocompensationfilterc.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiocomponentengine_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocomponentengine_vendor.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiocomponentenginec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocomponentenginec.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiocustparam_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocustparam_vendor.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiodcrflt_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiodcrflt_vendor.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiofmtconv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiofmtconv.so \
    vendor/realme/even/proprietary/vendor/lib/libaudioloudc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioloudc.so \
    vendor/realme/even/proprietary/vendor/lib/libaudioprimarydevicehalifclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioprimarydevicehalifclient.so \
    vendor/realme/even/proprietary/vendor/lib/libaudiotoolkit_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiotoolkit_vendor.so \
    vendor/realme/even/proprietary/vendor/lib/libbluetooth_audio_session_mediatek.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetooth_audio_session_mediatek.so \
    vendor/realme/even/proprietary/vendor/lib/liboplus_audio_config.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboplus_audio_config.so \
    vendor/realme/even/proprietary/vendor/lib/vendor.mediatek.hardware.audio@6.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.mediatek.hardware.audio@6.1.so \
    vendor/realme/even/proprietary/vendor/lib/vendor.mediatek.hardware.bluetooth.audio@2.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.mediatek.hardware.bluetooth.audio@2.1.so \
    
    vendor/realme/even/proprietary/vendor/lib64/hw/audio.primary.mt6768.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.mt6768.so \
    vendor/realme/even/proprietary/vendor/lib64/hw/audio.r_submix.mt6768.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.r_submix.mt6768.so \
    vendor/realme/even/proprietary/vendor/lib64/hw/audio.usb.mt6768.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.usb.mt6768.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudio_engineer_test.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudio_engineer_test.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudio_param_parser-vnd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudio_param_parser-vnd.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiocompensationfilter_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocompensationfilter_vendor.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiocompensationfilterc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocompensationfilterc.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiocomponentengine_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocomponentengine_vendor.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiocomponentenginec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocomponentenginec.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiocustparam_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocustparam_vendor.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiodcrflt_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiodcrflt_vendor.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiofmtconv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiofmtconv.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudioloudc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioloudc.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudioprimarydevicehalifclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioprimarydevicehalifclient.so \
    vendor/realme/even/proprietary/vendor/lib64/libaudiotoolkit_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiotoolkit_vendor.so \
    vendor/realme/even/proprietary/vendor/lib64/liboplus_audio_config.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liboplus_audio_config.so \
    vendor/realme/even/proprietary/vendor/lib64/vendor.mediatek.hardware.audio@6.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.mediatek.hardware.audio@6.1.so \
    vendor/realme/even/proprietary/vendor/lib64/vendor.mediatek.hardware.bluetooth.audio@2.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.mediatek.hardware.bluetooth.audio@2.1.so \
    
    
    vendor/realme/even/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_bluetooth_legacy_hal.xml \
    vendor/realme/even/proprietary/vendor/etc/bluetooth_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_audio_policy_configuration.xml \
    
    
    # ODM
    vendor/realme/even/proprietary/odm/etc/audio/audio_device/audio_device.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_device/audio_device.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_device/common/audio_device.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_device/common/audio_device.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/AudioParamOptions.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/BtInfo_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/HpImpedance_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/MicInfo_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackACF_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_ParamTreeView.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordDMNR_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordFIR_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVol_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_ParamTreeView.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVol_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SmartPa_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVol_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_ParamTreeView.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBCall_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBDevice_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VOW_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VOW_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VOW_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VOW_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVol_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_ParamTreeView.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2General_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Volume_AudioParam.xml \
    vendor/realme/even/proprietary/odm/etc/audio/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Volume_ParamUnitDesc.xml \
    vendor/realme/even/proprietary/odm/etc/audio/aurisys_config/aurisys_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config/aurisys_config.xml \
    vendor/realme/even/proprietary/odm/etc/audio/oplus_audio_features.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/oplus_audio_features.xml \
    vendor/realme/even/proprietary/odm/etc/audio/test_path/common/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/test_path/common/mixer_paths.xml \
    vendor/realme/even/proprietary/odm/etc/audio/test_path/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/test_path/mixer_paths.xml \
  

PRODUCT_PACKAGES += \
    EngineerMode
